image: Visual Studio 2017

platform:
  - x86

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 8 x86
  - yarn install
  - yarn add electron-builder@next --dev # force install next version to test electron-builder

build_script:
  - yarn dist

test: off

deploy:
  - release: CameraApp-v$(appveyor_build_version)
    auth_token:
      secure: 138ff167be8468c14158083365735c32233e7828
    provider: Github
    name: CameraApp
    artifact: /.*\.nupkg/            # upload all NuGet packages to release assets
    draft: false
    prerelease: false
    on:
      branch: master                 # release from master branch only
      appveyor_repo_tag: true        # deploy on tag push only
