image: Visual Studio 2017

platform:
  - x86

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 8 x86
  - yarn install
  - yarn add electron-builder@next --dev # force install next version to test electron-builder

build_script:
  - yarn dist

test: off

environment:
  access_token:
    secure: ue0uX6/HSCQhoH4Xbb6nkXNsxcPpQrx7VgGjo2sfa3Ot5rn6r3/ZzQ9CK6WiROhP

on_success:
  - git config --global credential.helper store
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
  - git config --global user.email "cuiyajie_dlut@hotmail.com "
  - git config --global user.name "cuiyajie"
  - git commit ...
  - git push ...